version: '3.8'

name: 'learn-rust-axum-rayato'

services:
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd

